require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '13.0'

target 'muuve_app_clone' do
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])

  rn_maps_path = '../node_modules/react-native-maps'
  pod 'react-native-google-maps', :path => rn_maps_path

  pod 'Firebase/Auth'
  pod 'Firebase/Analytics'

  pod 'react-native-splash-screen', :path => '../node_modules/react-native-splash-screen'

  target 'muuve_app_cloneTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  use_flipper!({ 'Flipper-Folly' => '2.3.0' })
  post_install do |installer|
    flipper_post_install(installer)
  end
end

target 'muuve_app_clone-tvOS' do
  # Pods for muuve_app_clone-tvOS

  target 'muuve_app_clone-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
